### ISSUE TITLE
Installer Issues - VISTA / WIN7

### ISSUE THREAD

**Issue by CompleteComputer** [TechnikEmpire/ss_issue_tracker#18]
Managed to manually get to work by installing the following:

http://www.microsoft.com/en-ca/download/details.aspx?id=5582

https://www.microsoft.com/en-ca/download/details.aspx?id=40784

http://hotfixv4.microsoft.com/Windows%207/Windows%20Server2008%20R2%20SP1/sp2/Fix398964/7600/free/446412_intl_x64_zip.exe

**Comment by TechnikEmpire** [comment]
Related #5

**Comment by TechnikEmpire** [comment]
Fixed
