### ISSUE TITLE
Browing Stops randomly after a period of time

### ISSUE THREAD

**Issue by CompleteComputer** [TechnikEmpire/ss_issue_tracker#21]
Browsing stops working at different time intervals. 2 of times, my local area connection showed no internet.

If I turn off the filter, internet is restored.

**Comment by TechnikEmpire** [comment]
Possibly related to #23 as this issue caused same effect on Win 8 x64 test machine.

**Comment by TechnikEmpire** [comment]
Closing for now assuming that #23 was the cause.
